openapi: "3.0.0"
info:
  title: Financial APIs - Generic Schemas
  version: 1.0.0
components:
  schemas:
    header:
      type: object
      properties:
        x-request-id:
          type: string
          description: A unique identifier for the request.
    BadRequest:
      type: object
      properties:
        message:
          type: string
          description: A description of the error.
        code:
          type: integer
          description: A numeric code for the error.
    Unauthorized:
      type: object
      properties:
        message:
          type: string
          description: A description of the error.
        code:
          type: integer
          description: A numeric code for the error.
           
    Forbidden:
      type: object
      properties:
        message:
          type: string
          description: A description of the error.
        code:
          type: integer
          description: A numeric code for the error.
    NotFound:
      type: object
      properties:
        message:
          type: string
          description: A description of the error.
        code:
          type: integer
          description: A numeric code for the error.
    ServerError:
      type: object
      properties:
        message:
          type: string
          description: A description of the error.
        code:
          type: integer
          description: A numeric code for the error.
    requestBodies: {}
    parameters: {}
    responses: {}
    headers: {}
    pathitems: {}
    examples: {}
paths: {}